import { describe, it, expect } from 'vitest'
import { resolveEnabled, generateInitEl } from './generator'
import { modules } from '../modules'

describe('resolveEnabled', () => {
  it('always includes required modules', () => {
    const result = resolveEnabled(new Set(), modules)
    const required = modules.filter((m) => m.required).map((m) => m.id)
    for (const id of required) {
      expect(result.has(id)).toBe(true)
    }
  })

  it('includes explicitly enabled modules', () => {
    const result = resolveEnabled(new Set(['theme', 'which-key']), modules)
    expect(result.has('theme')).toBe(true)
    expect(result.has('which-key')).toBe(true)
  })

  it('auto-enables org when org-capture is selected', () => {
    const result = resolveEnabled(new Set(['org-capture']), modules)
    expect(result.has('org')).toBe(true)
    expect(result.has('org-capture')).toBe(true)
  })

  it('auto-enables org when org-roam is selected', () => {
    const result = resolveEnabled(new Set(['org-roam']), modules)
    expect(result.has('org')).toBe(true)
    expect(result.has('org-roam')).toBe(true)
  })

  it('does not add modules that are not requested', () => {
    const result = resolveEnabled(new Set(['theme']), modules)
    expect(result.has('org')).toBe(false)
    expect(result.has('completion')).toBe(false)
  })
})

describe('generateInitEl', () => {
  const output = generateInitEl(new Set(['theme', 'which-key']), modules)

  it('starts with the header comment', () => {
    expect(output).toMatch(/^;;; init\.el --- Generated by initweave/)
  })

  it('ends with the footer comment', () => {
    expect(output.trimEnd()).toMatch(/;;; init\.el ends here$/)
  })

  it('includes required module elisp', () => {
    expect(output).toContain('use-package')
    expect(output).toContain('inhibit-startup-message')
  })

  it('includes enabled module elisp', () => {
    expect(output).toContain('ef-themes')
    expect(output).toContain('which-key-mode')
  })

  it('excludes disabled module elisp', () => {
    expect(output).not.toContain('vertico')
    expect(output).not.toContain('org-roam')
  })

  it('outputs modules in order', () => {
    const usePkgPos = output.indexOf('use-package bootstrap')
    const basicsPos = output.indexOf('Sensible defaults')
    const themePos = output.indexOf('Ef themes')
    expect(usePkgPos).toBeLessThan(basicsPos)
    expect(basicsPos).toBeLessThan(themePos)
  })

  it('includes lexical-binding file variable', () => {
    expect(output).toContain('-*- lexical-binding: t; -*-')
  })
})

describe('use-package :ensure hygiene', () => {
  const fullOutput = generateInitEl(
    new Set(modules.filter((m) => !m.required).map((m) => m.id)),
    modules
  )

  const builtins = ['org', 'eglot', 'tramp', 'flyspell']
  const thirdParty = ['ef-themes', 'magit', 'vertico', 'marginalia', 'orderless', 'org-roam',
    'corfu', 'projectile', 'auctex', 'ess', 'olivetti', 'deft',
    'markdown-mode', 'vterm', 'org-drill', 'which-key', 'denote']

  it('does not use use-package-always-ensure', () => {
    expect(fullOutput).not.toContain('use-package-always-ensure')
  })

  it('built-in packages are not passed to use-package with :ensure t', () => {
    for (const pkg of builtins) {
      // :ensure should appear on the very next non-blank line after (use-package <pkg>)
      const ensureTPattern = new RegExp(`\\(use-package ${pkg}\\s+:ensure t`)
      expect(fullOutput, `${pkg} should not have :ensure t`).not.toMatch(ensureTPattern)
    }
  })

  it('third-party packages have :ensure t', () => {
    for (const pkg of thirdParty) {
      const ensureTPattern = new RegExp(`\\(use-package ${pkg}\\s+:ensure t`)
      expect(fullOutput, `${pkg} should have :ensure t`).toMatch(ensureTPattern)
    }
  })
})
