import type { Module } from '../modules'

export interface CustomBlock {
  id: string
  label: string
  elisp: string
  enabled: boolean
}

/**
 * Generate a complete init.org string (suitable for org-babel-tangle) from
 * a set of enabled module IDs and any AI-generated custom blocks.
 */
export function generateOrgFile(
  enabledIds: Set<string>,
  modules: Module[],
  customBlocks: CustomBlock[] = []
): string {
  const resolved = resolveEnabled(enabledIds, modules)
  const date = new Date().toISOString().slice(0, 10)

  const preamble = `#+TITLE: Emacs Configuration
#+DATE: ${date}
#+PROPERTY: header-args:emacs-lisp :tangle ~/.emacs.d/init.el
#+STARTUP: overview

Generated by [[https://initweave.com][initweave]] on ${date}.
Edit freely — re-generate any time to pick up new modules.

To install: open this file in Emacs and run =M-x org-babel-tangle=.
Emacs will write =~/.emacs.d/init.el= and install all packages on first restart.

`

  const enabledModules = modules
    .filter((mod) => resolved.has(mod.id))
    .sort((a, b) => a.order - b.order)

  const moduleSections = enabledModules.map((mod, i) => {
    const elispContent =
      i === 0
        ? `;;; -*- lexical-binding: t -*-\n\n${mod.elisp.trim()}`
        : mod.elisp.trim()
    return `* ${mod.label}\n\n${mod.description}\n\n#+begin_src emacs-lisp\n${elispContent}\n#+end_src`
  })

  const customSections = customBlocks.map(
    (block) =>
      `* ${block.label} /(AI-generated)/\n\n#+begin_src emacs-lisp\n${block.elisp.trim()}\n#+end_src`
  )

  return preamble + [...moduleSections, ...customSections].join('\n\n') + '\n'
}

/**
 * Given a set of explicitly enabled module IDs, return a new set that also
 * includes any required dependencies. Required modules are always included.
 */
export function resolveEnabled(ids: Set<string>, modules: Module[]): Set<string> {
  const resolved = new Set<string>()

  // Always add required modules
  for (const mod of modules) {
    if (mod.required) {
      resolved.add(mod.id)
    }
  }

  // Add explicitly enabled modules
  for (const id of ids) {
    resolved.add(id)
  }

  // Resolve dependencies (single level is sufficient for current schema)
  let changed = true
  while (changed) {
    changed = false
    for (const mod of modules) {
      if (resolved.has(mod.id) && mod.dependsOn && !resolved.has(mod.dependsOn)) {
        resolved.add(mod.dependsOn)
        changed = true
      }
    }
  }

  return resolved
}

/**
 * Generate a complete init.el string from a set of enabled module IDs
 * and any AI-generated custom blocks.
 */
export function generateInitEl(
  enabledIds: Set<string>,
  modules: Module[],
  customBlocks: CustomBlock[] = []
): string {
  const resolved = resolveEnabled(enabledIds, modules)

  const date = new Date().toISOString().slice(0, 10)
  const header = `;;; init.el --- Generated by initweave on ${date}  -*- lexical-binding: t; -*-

;; This file was generated by https://initweave.com
;; Edit it freely — re-generate any time to pick up new modules.

`
  const footer = `\n;;; init.el ends here\n`

  const moduleBlocks = modules
    .filter((mod) => resolved.has(mod.id))
    .sort((a, b) => a.order - b.order)
    .map((mod) => `;;; ${mod.label}\n\n${mod.elisp.trim()}\n`)

  const customParts = customBlocks.map(
    (block) => `;;; ${block.label} (AI-generated)\n\n${block.elisp.trim()}\n`
  )

  const allBlocks = [...moduleBlocks, ...customParts]
  return header + allBlocks.join('\n\n') + footer
}
